version: "3.4"
services:
  holeshot.dev:
    container_name: holeshot.dev
    build:
      context: ./
      dockerfile: ./.devcontainer/Dockerfile
    environment:
      DOCKER_HOST: unix:///var/run/docker-host.sock
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: S3RVER
      AWS_SECRET_ACCESS_KEY: S3RVER
    command: sleep infinity

  holeshot.cognito:
    container_name: holeshot.cognito
    image: jagregory/cognito-local:latest
    ports:
      - "9229:9229"
    volumes:
      - ./.devcontainer/.cognito:/app/.cognito

  holeshot.sfn:
    container_name: holeshot.sfn
    image: amazon/aws-stepfunctions-local
    ports:
      - "8083:8083"
    environment:
      AWS_ACCOUNT_ID: 146665891952
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: S3RVER
      AWS_SECRET_ACCESS_KEY: S3RVER
      # WAIT_TIME_SCALE: VALUE
      LAMBDA_ENDPOINT: http://holeshot.sls:3002
      # BATCH_ENDPOINT: VALUE
      DYNAMODB_ENDPOINT: http://holeshot.dynamodb:8000
      # ECS_ENDPOINT: VALUE
      # GLUE_ENDPOINT: VALUE
      # SAGE_MAKER_ENDPOINT: VALUE
      # SQS_ENDPOINT: VALUE
      SNS_ENDPOINT: http://holeshot.sls:4002

  holeshot.dynamodb:
    container_name: holeshot.dynamodb
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - ./.devcontainer/.db:/home/dynamodblocal/db
    command:
      [
        "-jar",
        "DynamoDBLocal.jar",
        "-sharedDb",
        "-dbPath",
        "/home/dynamodblocal/db",
      ]

  holeshot.dynamodb.admin:
    container_name: holeshot.dynamodb.admin
    image: aaronshaf/dynamodb-admin
    ports:
      - 8001:8001
    environment:
      DYNAMO_ENDPOINT: http://holeshot.dynamodb:8000

  holeshot.sls:
    container_name: holeshot.sls
    image: node:16
    # Custom docker build that will run dotnet support branch of serverless-offline
    # build:
    # context: .
    # dockerfile: ./.devcontainer/sls-local.Dockerfile
    tty: true
    stdin_open: true
    ports:
      - "3000:3000" # For api gateway rest endpoints
      - "3001:3001" # For api gateway based websockets
      - "3002:3002"
      - "4002:4002"
      - "4569:4569" # S3
      - "8005:8005" # for serverless-offline-ses-v2
      - "9228:9228" # node debugger
    environment:
      AWS_ACCOUNT_ID: 146665891952
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: S3RVER
      AWS_SECRET_ACCESS_KEY: S3RVER
    working_dir: /sls-offline
    command: sh -c "npm install -g pnpm && pnpm run sls:start"
    volumes:
      - .:/sls-offline

  holeshot.web:
    container_name: holeshot.web
    image: node:16
    ports:
      - "8080:8080"
    working_dir: /vite-client
    command: sh -c "npm install -g pnpm && pnpm run dev:client:docker"
    volumes:
      - .:/vite-client

  holeshot.storybooks:
    container_name: holeshot.storybooks
    image: node:16
    ports:
      - "6006:6006"
    working_dir: /workspace
    command: sh -c "npm install -g pnpm && pnpm run deploy-storybook:local && npx http-server -p 6006 storybooks"
    volumes:
      - .:/workspace
