# GetTracksCompleteTopic:
#   Type: "AWS::SNS::Topic"
#   Properties:
#     DisplayName: ${self:service}-GetTracksCompleteTopic

${self:service}Bucket:
  Type: AWS::S3::Bucket
  Properties:
    BucketName: holeshot-bmx.com-crawler
    BucketEncryption:
      ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
