name: "Deploy System"

on:
  push:
    branches:
      - main

jobs:
  deployment:
    name: "Deployment"

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      # TODO: switch this to pull config from a file on s3 somewhere...
      - name: Bootstrap & Build
        run: |
          npm install -g pnpm
          pnpm i && cd ./packages/vue2-client
          echo 'VITE_APP_CLIENT_ID=${{ secrets.APP_CLIENT_ID }}' > .env
          echo 'VITE_APP_POOL_ID=${{ secrets.APP_POOL_ID }}' >> .env
          echo 'VITE_APP_HOST=${{ secrets.APP_HOST }}' >> .env
          echo 'VITE_APP_AGENT=${{ secrets.APP_AGENT }}' >> .env
          echo 'VITE_APP_API=${{ secrets.APP_API }}' >> .env
          echo 'VITE_APP_SERVICE_WORKER_PATH=service-worker.js' >> .env
          echo 'VITE_APP_WEBSOCKET=${{ secrets.APP_WEBSOCKET }}' >> .env
          cd ../..
          pnpm run build:client
          pnpm run sls:webpack && cd .serverless && unzip holeshot.zip

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: "Bootstrap, Deploy CDK, & sync S3 media "
        working-directory: ./infrastructure
        env:
          AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          NODE_ENV: production
        run: |
          pnpm run cdk bootstrap aws://${{ secrets.AWS_ACCOUNT_ID }}/${{ secrets.AWS_REGION }}
          pnpm run deploy
          cd ../media && aws s3 sync . s3://images.holeshot-bmx.com
