name: Publish main branch Storybook

on:
  push:
    branches: [main]
    # paths:
    #   - packages/holeshot-plugin/src/stories/**
    #   - packages/holeshot-plugin/src/components/**
    #   - packages/holeshot-plugin/src/styles/**

jobs:
  storybook:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          path: main

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 19

      - name: npm install and lerna bootstrap
        run: |
          cd $GITHUB_WORKSPACE/main
          npm install -g npm@latest
          npm install silent
          npm run bootstrap

      - name: Run unit tests
        run: |
          cd $GITHUB_WORKSPACE/main
          npm run test

      - name: Build Storybook
        run: |
          cd $GITHUB_WORKSPACE/main
          cd packages/holeshot-plugin
          npm run deploy-storybook -- --out=storybook --dry-run

      - name: Checkout storybook
        uses: actions/checkout@v2
        with:
          ref: storybook
          path: storybook

      - name: Commit Storybook to storybook branch #storybook branch must exist
        run: |
          cd $GITHUB_WORKSPACE/storybook
          cp $GITHUB_WORKSPACE/main/packages/holeshot-plugin/storybook/* $GITHUB_WORKSPACE/storybook
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add .

          if git diff-index --quiet HEAD --; then
              echo 'No changes to commit';
          else
              git commit -m "Deploying main branch Storybook to GitHub Pages 🚀";
              git push;
          fi
